CREATE DATABASE IF NOT EXISTS chantelle_invitation
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE chantelle_invitation;

CREATE TABLE IF NOT EXISTS guests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  guest_name VARCHAR(180) NOT NULL,
  contact_number VARCHAR(60) NOT NULL,
  bring_count INT UNSIGNED NOT NULL DEFAULT 0,
  companions_json JSON NOT NULL,
  adult_count INT UNSIGNED NOT NULL DEFAULT 0,
  kid_count INT UNSIGNED NOT NULL DEFAULT 0,
  allergies TEXT NULL,
  car_plate_number VARCHAR(80) NULL,
  confirmed TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
